-- CreateEnum
CREATE TYPE "CloseReason" AS ENUM ('CHAT_REPORT', 'VC_REPORT', 'DMS_REPORT', 'OFF_PLATFORM_REPORT', 'OTHER_REPORT', 'MOD_GENERATED_CHAT_INTERVENTION', 'MOD_GENERATED_VC_INTERVENTION', 'MOD_GENERATED_DMS_INTERVENTION', 'MOD_GENERATED_PROFILE_INTERVENTION', 'MOD_GENERATED_OFF_PLATFORM_INTERVENTION', 'SPAM_TICKET', 'INVALID_TICKET', 'SUGGESTION', 'MODERATION_COMPLAINT', 'EVENT', 'GREETER_ENQUIRY', 'STAFF_APP_ENQUIRY', 'OTHER');

-- AlterTable
ALTER TABLE "Ticket" ADD COLUMN     "closeDescription" TEXT,
ADD COLUMN     "closeReason" "CloseReason";
